name: CI/CD for Even Number Checker

on: 
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Check Jest installation
        run: which jest

      - name: List project files
        run: ls -R

      - name: Run tests
        run: npm test

      - name: Finish message
        run: echo "Тестирование завершено!"
